experiment_name: crowd_mnv2_s8
input_size: [512, 512]
output_stride: 8
alpha: 1.0
weights: imagenet      # ou null para treinar do zero
train_backbone: true  # libere depois de aquecer se quiser
head_filters: 192
dilation_rates: [2, 4, 8]
use_separable: true
density:
  mode: adaptive            # usa sigma adaptativo por k-NN
  k: 3
  beta: 0.3
  min_sigma: 1.0
